### ISSUE TITLE
Norwegian keymap

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#100]
```
I made a keymap for norwegian keyboards.

```

Original issue reported on code.google.com by `herman.t...@gmail.com` on 10 Dec 2012 at 11:31

Attachments:
* [no.map](https://storage.googleapis.com/google-code-attachments/logkeys/issue-100/comment-0/no.map)

**Comment by jzohrab** [comment]
Code already contains an no.map added as at Nov 10 2015.  Am assuming that the committed map is correct.
