### ISSUE TITLE
swiss german keymap

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#102]
```
I manually made a swiss german keymap. (on Ubuntu 12.10 with logkeys v0.1.1a)
```

Original issue reported on code.google.com by `jan.herm...@gmail.com` on 26 Dec 2012 at 2:25

Attachments:
* [de-ch.map](https://storage.googleapis.com/google-code-attachments/logkeys/issue-102/comment-0/de-ch.map)

**Comment by jzohrab** [comment]
Duplicate of https://github.com/kernc/logkeys/issues/121, closing.
