### ISSUE TITLE
Store data to database

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#115]
```
Is it possible to store log file data directly to database?
I would like to use the HTTP Post method to upload all data to MySQL database. 
This way I will have "DateTime, keys_pressed_before_ENTER" in a table.

Thank you!
```

Original issue reported on code.google.com by `prassaschr@gmail.com` on 24 Dec 2013 at 8:41

**Comment by jzohrab** [comment]
@kernc - I'd close this one, for a few reasons:

- in the *nix tradition, this tool should do one thing and one thing only: write to files.  Well, you could abstract it a bit more, but it's already sufficient.
- People have the logs already, if they want they can set up a job to move the files, process them further, etc.  If this tries to do more, then you have more chances for bug reports.

This is 2 years old as well, maybe just get rid of old open issues. :-)

**Comment by kernc** [comment]
I haven't really been maintaining this software ... in a while. Also don't see this changing anytime soon. :sweat_smile:

**Comment by jzohrab** [comment]
@kernc - do you want to add me as a maintainer of this repo?  The google code repo redirects to here.  I'm happy to crank through some of this stuff in return for being able to use it for a work project.

**Comment by kernc** [comment]
> in return for being able to use it for a work project?

What do you mean by work project? The license grants any use you want. :smile:

**Comment by jzohrab** [comment]
:-) yep!  Thanks very much.
