### ISSUE TITLE
de_CH.map 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#121]
```
Works fine.


```

Original issue reported on code.google.com by `bachi.in...@gmail.com` on 26 Aug 2014 at 10:31

Attachments:
* [de_CH.map](https://storage.googleapis.com/google-code-attachments/logkeys/issue-121/comment-0/de_CH.map)

**Comment by kernc** [comment]
@jzohrab The two attached de_CH keymaps in #121 and #102 are not the same. How did you decide for this one?
