### ISSUE TITLE
Keymap files

### ISSUE THREAD

**Issue by mogaal** [kernc/logkeys#130]
Hello, I need to download the keymap. The export option does't work fine so I need the official one (I remember I could find it in the old webpage but not I am redirected to the github webpage)

Regards

**Comment by Kluts** [comment]
For all of you out there who want the keymap files... After a bit of Google I found them at:

http://wiki.logkeys.googlecode.com/git/Keymaps.wiki

To be more precise, they are:


* http://wiki.logkeys.googlecode.com/git/keymaps/en_GB.map English (UK)
* http://wiki.logkeys.googlecode.com/git/keymaps/fr_CH.map French (CH)
* http://wiki.logkeys.googlecode.com/git/keymaps/fr.map French (FR)
* http://wiki.logkeys.googlecode.com/git/keymaps/fr-dvorak-bepo.map French (Bepo keyboard)
* http://wiki.logkeys.googlecode.com/git/keymaps/de.map German
* http://wiki.logkeys.googlecode.com/git/keymaps/hu.map Hungarian
* http://wiki.logkeys.googlecode.com/git/keymaps/it.map Italian
* http://wiki.logkeys.googlecode.com/git/keymaps/no.map Norwegian
* http://wiki.logkeys.googlecode.com/git/keymaps/pt_BR.map Portuguese (Brazil)
* http://wiki.logkeys.googlecode.com/git/keymaps/pt_PT.map Portuguese (Portugal)
* http://wiki.logkeys.googlecode.com/git/keymaps/ro.map Romanian
* http://wiki.logkeys.googlecode.com/git/keymaps/ru.map Russian
* http://wiki.logkeys.googlecode.com/git/keymaps/sk_QWERTY.map Slovak (QWERTY)
* http://wiki.logkeys.googlecode.com/git/keymaps/sk_QWERTZ.map Slovak (QWERTZ)
* http://wiki.logkeys.googlecode.com/git/keymaps/sl.map Slovene
* http://wiki.logkeys.googlecode.com/git/keymaps/es_AR.map Spanish (Argentina)
* http://wiki.logkeys.googlecode.com/git/keymaps/es_ES.map Spanish (Spain)
* http://wiki.logkeys.googlecode.com/git/keymaps/sv.map Swedish
* http://wiki.logkeys.googlecode.com/git/keymaps/tr.map Turkish

Maybe someone should do a pull request to add them to this repository.

**Comment by Kluts** [comment]
This can be closed now, #131 took care of it and now all keymap files are included in the repo.

**Comment by kernc** [comment]
Thanks again, @Kluts.

**Comment by Kluts** [comment]
My pleasure!
