### ISSUE TITLE
Please tag the releases.

### ISSUE THREAD

**Issue by SanskritFritz** [kernc/logkeys#137]
There are no releases, please tag he repo and update the news file.

**Comment by kernc** [comment]
Thanks. ICBA to confirm by diffing tar balls, but IIRC, [HEAD~6](https://github.com/kernc/logkeys/commit/aa0812690df40e97ec188d22527f4197542e7670) was never properly released.

**Comment by SanskritFritz** [comment]
I didn't get what you mean. I would like to be able to download release tarballs for packaging. On google code we had version tarballs, for example 0.1.1a was the latest release IIRC. It is even stated in the changelog file.

**Comment by kernc** [comment]
Shit, there is a changelog file! I honestly wasn't aware! :smiley: 
[This](https://github.com/kernc/logkeys/archive/master.tar.gz) should be the best option for downloading if at all. You can tag it `0.1.2~git78321c6`, if you want.

**Comment by SanskritFritz** [comment]
Is this the official successor of logkeys? Is there stable version releases planned?

**Comment by kernc** [comment]
This repo is migrated from Google Code. The software, however, is, at best, completely unmaintained.

If you'd like to make a release, you are welcome to (code is WTFPL). I can give a fairly reliable assurance that the current master will remain as _stable_ as it is at this moment. :smile:

**Comment by SanskritFritz** [comment]
OK thanks for the heads-up. That means, I have to delete this package: https://aur.archlinux.org/packages/logkeys/

**Comment by kernc** [comment]
Unfortunately, that might be the case, yes.

**Comment by SanskritFritz** [comment]
Thanks for your time and help.

**Comment by SanskritFritz** [comment]
Hey, you said you will not touch it! :D

**Comment by kernc** [comment]
Indeed. :sweat_smile: But then just a week or two later @jzohrab came and offered help and it's been stellar since. :star2: 
I've tagged for you the past releases, as I believe them to be. The next one, if any, will be JZ's, I hope. :)

**Comment by SanskritFritz** [comment]
That's cool. So will we have release tags from now on? Then I can revive the stable logkeys package.

**Comment by jzohrab** [comment]
I don't have any experience with releases here, but would be good to get something like that rolling with proper tagging and getting into public repos like yum and apt.  Zero experience on that as well.  :-)  Docs on doing that would be good.

Yes, we should tag releases.  It would be good to have some formal testing so that the releases can be certified good.  This may be overkill for this project, but this is a good way to get some exposure/experience to public release cycles.

**Comment by jzohrab** [comment]
Maybe we should reopen this issue.  @SanskritFritz thoughts?

**Comment by SanskritFritz** [comment]
It's fine with me, if I reopen it, you actually commit to do it :D

**Comment by jzohrab** [comment]
If there are docs around releasing, I'll follow them.  I'm very familiar with git, but am not so sure how to go about managing releases for an open source project.  If you can help start those docs, I'd appreciate it.

**Comment by SanskritFritz** [comment]
There is not much to do I think. You just update the changelog file, and tag the release. Basically that's it I think. Oh btw, please update the install instructions, ./autogen step is missing.

**Comment by kernc** [comment]
That's right; I believe it goes something like:
* update the changelog,
* bump the version,
* make a tarball,
* ensure it builds,
* git tag the commit.

If you forget any of the steps, you can always amend it later. :laughing:

**Comment by jzohrab** [comment]
Is version bumping a change in configure.ac only?
Does the tarball get posted anywhere, or is it just a local test?
We can script out everything.

@SanskritFritz - in master branch INSTALL file, `$ ./autogen.sh` is there.  Were you looking somewhere else?

**Comment by SanskritFritz** [comment]
Yeah, I meant docs/Documentation.md

**Comment by kernc** [comment]
> Does the tarball get posted anywhere, or is it just a local test?

The tagged commit gets a tarball posted on the [releases page](https://github.com/kernc/logkeys/releases).

**Comment by jzohrab** [comment]
Great, thanks.  We should do a release soon to get the process documented in the code and to include the recent changes.  In terms of testing releases, I'm still not sure how to handle that, as we don't have real tests defined in the code (automated tests, that is), nor do we have OSs to compile on, unless we create a bunch of Vagrant boxes with different OS flavors and commit that here as well.

**Comment by kernc** [comment]
We could also live with a [Travis](https://travis-ci.org/) build being run on each commit to master an pull requests, since it doesn't require any of our resources. It's Ubuntu 12.04 only ATM, but the pangolin is precise! :smiley_cat:

**Comment by SanskritFritz** [comment]
I love to see logkeys is semi-maintained again 👍 
Since there are releases again, I can close this ticket.
