### ISSUE TITLE
An issue on how to handle open issues

### ISSUE THREAD

**Issue by jzohrab** [kernc/logkeys#141]
Many of these have been auto-imported from Google.  Is the google code repo still active?  Where are these feature requests coming from?

I think a few should be closed, I'll go through and close them.  Is there a corresponding site on Google where the issues are recorded that should be tended as well?

**Comment by kernc** [comment]
[Google Code shut down](http://google-opensource.blogspot.si/2015/03/farewell-to-google-code.html) in favor or GitHub. All the issues (except the most recent ones) had been imported.

I'm sure some should be closed outright; also many are duplicates. Some are relevant, though, particularly https://github.com/kernc/logkeys/issues/28, where I hunch [pc105 vs pc104 vs. etc. keyboard models](https://github.com/linuxmint/live-installer/blob/master/usr/lib/live-installer/frontend/generate_keyboard_layout.py) to be the cause. And then there's something with users experiencing empty log files. Invalid use of `freopen`+forking might be the issue. And there are keymaps.

Were I to start, I'd also go over [distributions](http://sources.debian.net/src/logkeys/0.1.1a%2Bgit5ef6b0dcb9e3-2/debian/patches/) [patches](https://aur.archlinux.org/logkeys.git/logkeys-stdout.patch) and see what they fix.

I should trust your good judgement. After all, you are the maintainer of this project. Congratulations! :tada: :smiley:

**Comment by jzohrab** [comment]
If we close issues, will the ppl who opened them be pinged?

I can update the readme etc to point to the 'issues' here, clear up how releases are done, etc.  I don't know if I'm the maintainer long-term, but can do so for now.  Also need to figure out how to get the release into ubuntu's apt repo.

**Comment by kernc** [comment]
> If we close issues, will the ppl who opened them be pinged?

Only when the OP isn't @GoogleCodeExporter.

You seem reasonable. As far as I'm concerned, whatever you want. Any maintenance/help you can give will be appreciated. No expectations.

logkeys is [already in Ubuntu](http://packages.ubuntu.com/search?keywords=logkeys&searchon=names&suite=all&section=all) because it is [in Debian](https://packages.debian.org/search?keywords=logkeys). Find a way to update it in Debian and Ubuntu will follow. :smiley_cat:

**Comment by jzohrab** [comment]
OK, thanks @kernc.  I'll think a bit about how to proceed with changes here.  I'll do PRs for anything big for your review and sanity check.  I'll work out the branch to commit to - I'm not sure what a good branching policy is for this, if you shoot me a link I'll read up.  I see the stable branch there, thanks.

**Comment by kernc** [comment]
Sounds good to me. Thanks. I wouldn't worry too much, I've never even bothered (noob) to tag releases. Pull requests sound nice as that way I get an email and can follow along.

**Comment by jzohrab** [comment]
OK thanks, will get some docs started and then will close this issue then.

**Comment by jzohrab** [comment]
https://github.com/kernc/logkeys/pull/142 will sort-of cover this.  Will work out the rest as we go.
