### ISSUE TITLE
CS keymap

### ISSUE THREAD

**Issue by azazel80** [kernc/logkeys#145]
CS keymap layout tested with Linux
[cs.map.zip](https://github.com/kernc/logkeys/files/127915/cs.map.zip)

**Comment by kernc** [comment]
CS as in `cs_CZ`?

**Comment by azazel80** [comment]
Yes, sorry... cs_CZ.UTF-8

**Comment by jzohrab** [comment]
Merged into master, thanks @azazel80 for the contribution.
