### ISSUE TITLE
why i can not configure?

### ISSUE THREAD

**Issue by mutepigz** [kernc/logkeys#148]
when I input `../configure` to install it,i got this`../configure: No such file or directory`,and there is nothing in `/build` ,how to solve this problem?

**Comment by jzohrab** [comment]
Hello, please provide more detail.

1. How did you install this?
2. What were the exact steps you took to get the error?  What directory were you in when you typed `../configure`?  Had you installed, or were you running from source?
3. What OS are you using? (not really relevant ...)

Thanks, jz

**Comment by mutepigz** [comment]
OK I GOT IT,,,Thanx

**Comment by kernc** [comment]
You are supposed to [run _autogen.sh_ first](https://github.com/kernc/logkeys/blob/master/INSTALL) and it should be passing without issues.
