### ISSUE TITLE
_empty log file or 'Error opening input event device'

### ISSUE THREAD

**Issue by andsild** [kernc/logkeys#150]
I use a USB keyboard on a laptop. The laptop keyboard logs all keystrokes, but none on the USB keyboard. Not sure if this a bug per se, but thought I'd report. The keyboard is somewhat special in that it is a split keyboard (althought only 1 usb port, [here,](https://www.google.no/search?q=kinesis+freestyle&oq=kinesis+freestyle&aqs=chrome..69i57.2783j0j7&sourceid=chrome&ie=UTF-8) if you want to have a look)

(I use evtest to determine that its /dev/input/event16)

/proc/bus/input/devices:
[devices.txt](https://github.com/kernc/logkeys/files/248687/devices.txt)

**Comment by kernc** [comment]
Yes, logkeys uses the first recognized keyboard by default, i.e. the integrated one, _/dev/input/event3_. If you want to specify a different keyboard device, you can use the `--device` switch, e.g.:
```bash
logkeys --start -d event16
```
