### ISSUE TITLE
eventX is guessed wrong

### ISSUE THREAD

**Issue by lislon** [kernc/logkeys#154]
When I run logkeys with default arguments, I only see Logging started...' and 'Logging stopped...' in logs.

Logkeys is using `event0`:

```
# logkeys --start
# lsof -p `pgrep logkey` | grep event 
logkeys 19238 root    0r   CHR  13,64      0t0    2478 /dev/input/event0
```

However when I set to  `event3` it works!

[Here](https://gist.github.com/lislon/637e521d323c4af3b40aa74301b48ea1) is output of my `/proc/bus/input/devices`

**Comment by kernc** [comment]
Yes, logkeys uses the first device that has `EV=120013`. @jzohrab explained [somewhere on the issue tracker](https://github.com/kernc/logkeys/pull/139#issuecomment-180874306) what the value means. You can always override the used device with a switch. Or just use the other keyboard ("COMPANY USB Device"). :smiley:
