### ISSUE TITLE
Problem in Makefile.am ?

### ISSUE THREAD

**Issue by Ymil** [kernc/logkeys#157]
After executing ./autogen whit automake (1:1.14.1-4) in debian jessi, report

```
 Regenerating autotools files ...
src/Makefile.am:1: warning: 'CXXFLAGS' is a user variable, you should not override it;
src/Makefile.am:1: use 'AM_CXXFLAGS' instead

```

In line 0 the filename src/Makefile.am change the name vars, and change help the file autogen.sh.

> echo "   cd build; ../configure; make; su; make install"

To

> echo "   cd build; sudo ../configure; sudo make; sudo make install"

After executing su in the shell, a new console opens and dont execute the make install sentence.

**Comment by kernc** [comment]
Fixed in https://github.com/kernc/logkeys/commit/9825a8b8b9e19f83f2673e98395dbf0bff7c0faf.

If the example containing administrative commands is not copy-pastable directly, let's agree to consider this as a feature! :smile:
