### ISSUE TITLE
Invalid event ID for das keyboard

### ISSUE THREAD

**Issue by mojoiskewl** [kernc/logkeys#160]
Used event id = 5

Attached is my /proc/bus/input/devices files

Hopefully this helps somebody out
[inputdevices.txt](https://github.com/kernc/logkeys/files/543490/inputdevices.txt)

**Comment by charlesbrandt** [comment]
I also hit this condition in the "Troubleshooting" section of README.md. For me, the working one was:

    sudo cat /dev/input/event12

[input_devices.txt](https://github.com/kernc/logkeys/files/2288917/input_devices.txt)
