### ISSUE TITLE
It's Started ... but not work.

### ISSUE THREAD

**Issue by Taylor102** [kernc/logkeys#166]
When I installed my vps  centos 7 etc. [GNU/UNIX] and logkeys start log file is  created and says Started... but nothing anymore.

I connecnted via putty.

I guess this issue TTY in /dev/ file.

**Comment by kernc** [comment]
logkeys works with hardware keyboards. Doesn't work over SSH.
https://github.com/kernc/logkeys/issues/163#issuecomment-283747110
