### ISSUE TITLE
Launch several instances for X keyboards

### ISSUE THREAD

**Issue by SwiTool** [kernc/logkeys#167]
For example, we could have 2 or more QR Code scanner (or RFID tag scanner), then it would be nice to launch the program X times, specific on each "keyboard".

**Comment by kernc** [comment]
I believe this should be possible using `-d` switch to set each scanner's device and `--no-daemon` to prevent process from becoming a daemon and creating an exclusive PID file?

```bash
# print to stdout characters read from scanner 3
logkeys --no-daemon -o - -d event3 &
# print to stdout characters read from scanner 4
logkeys --no-daemon -o - -d event4 &
```

**Comment by SwiTool** [comment]
Indeed that's functionnal.
Thank you ! :)
