### ISSUE TITLE
"A GNU/Linux keylogger that worked!"

### ISSUE THREAD

**Issue by kanihal** [kernc/logkeys#168]
it doesn't work now???

**Comment by kernc** [comment]
Does it work? I don't know. It did work at a time nothing else did. That's the claim, I presume.

**Comment by kanihal** [comment]
It doesn't work on 16.04.  it says
```
Logging started ...

2017-07-22 19:37:06+0530 > 

Logging stopped at 2017-07-22 19:43:29+0530

```

nothing gets logged in between.
