### ISSUE TITLE
sh: /usr/etc/logkeys-start.sh: No such file or directory

### ISSUE THREAD

**Issue by Hritik14** [kernc/logkeys#169]
Installed logkeys with blackarch repo on Arch linux.
logkeys version: 0.1.1a

`llk`
sh: /usr/etc/logkeys-start.sh: No such file or directory
`sudo llk`
sh: /usr/etc/logkeys-start.sh: No such file or directory
`logkeys`
logkeys: Got r00t?

Last command works successfully and when ran with root, starts logging as well.
I think there are some issues with llk and llkk files.

**Comment by SanskritFritz** [comment]
Hi I'm the maintainer of the logkeys package in the AUR. Sorry for the mistake, now the files are installed again.
I also have reintroduced the stable logkeys package along with logkeys-git.

**Comment by kernc** [comment]
Thanks @SanskritFritz!
