### ISSUE TITLE
with caps lock on, letters logged as lowercase

### ISSUE THREAD

**Issue by bdantas** [kernc/logkeys#173]
When I make uppercase letters by holding down shift key, log shows uppercase letters as expected.

When I make uppercase letters by turning on caps lock, log unexpectedly shows lowercase letters. 

Is there a fix for this? I rely on the ingenious logkeys for my custom international keyboard (http://dev1galaxy.org/viewtopic.php?id=1639), which works almost perfectly except for the caps lock issue.

Thanks!

**Comment by kernc** [comment]
Agreed, this should work. Pull requests welcome.

**Comment by bdantas** [comment]
Alas, I have never worked with C++. I will take at the code but doubt I have the skills to implement this.

**Comment by kernc** [comment]
With the current architecture, it might be easiest to just follow the <kbd>Shift</kbd> key example: https://github.com/kernc/logkeys/blob/f818e112e45360030eb4bc8f98f6e112ce311aa9/src/logkeys.cc#L475

**Comment by bdantas** [comment]
Solved with commit 5c368327a2cd818efaed4794633c260b90b87abf
