### ISSUE TITLE
records gibberish

### ISSUE THREAD

**Issue by tkalfaoglu** [kernc/logkeys#175]
while it was working fine for some time, now the application records gibberish -- nothing like what is typed. What is recorded is illegible. This is on a national (non-US/UK) keyboard.

**Comment by kernc** [comment]
Was the keyboard perhaps changed? Reviewing the [commit log](https://github.com/kernc/logkeys/commits/master), one can see not much has changed recently that would seem related. The [keymapping code](https://github.com/kernc/logkeys/blob/master/src/keytables.cc) had always been flakey, defunct for either pc104 or pc105 keyboards; can't remember.

**Comment by tkalfaoglu** [comment]
the same computer with the same keyboard. it used to work fine some months back.

**Comment by kernc** [comment]
Were you perhaps using one of the [pre-provided keymaps](https://github.com/kernc/logkeys/tree/master/keymaps) before?

**Comment by kernc** [comment]
Probably a duplicate of https://github.com/kernc/logkeys/issues/162.
