### ISSUE TITLE
Log keys from virtual device - no Phys is listed in /proc/bus/input/devices

### ISSUE THREAD

**Issue by falz** [kernc/logkeys#178]
Hi there, I just discovered this and was looking to debug some ghost keyboard inputs I get from a Raspberry pi project using its GPIO keys to more or less emulate a keyboard, sort of.

I'm using Pikeyd (https://github.com/mmoller2k/pikeyd/) which lets one map keyboard commands to GPIO pins. This does indeed show up in /proc/bus/input/devices but lists as virtual, with no Phys listed, so I cannot declare this device.

Snippet from proc/bus/input/devices looks like this:

I: Bus=0003 Vendor=0001 Product=0001 Version=0001
N: Name="uinput-sample"
P: Phys=
S: Sysfs=/devices/virtual/input/input4
U: Uniq=
H: Handlers=sysrq kbd event4 rfkill 
B: PROP=0
B: EV=100003
B: KEY=ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

.. which jives with name in the code (https://github.com/mmoller2k/pikeyd/blob/master/uinput.c).

Curious if there's an existing way to specify device in some other way, such as this S / Sysfs mapping? Nothing in the --help output seems to indicate it, just trying to confirm.

Thanks!

**Comment by kernc** [comment]
`sudo logkeys --no-daemon --start --device event4` doesn't work?

**Comment by falz** [comment]
derp it totally does actually. I was looking at the contents of /dev/input/by-path/ and /dev/input/by-id/, event4 doesnt show in either and somehow I didn't correlate them.

Sorry for the static, things seem to work great- much appreciated!

**Comment by kernc** [comment]
No problem. Glad it works for you. 😄
