### ISSUE TITLE
Custom action after certain number of key presses

### ISSUE THREAD

**Issue by Fandekasp** [kernc/logkeys#189]
Is it possible to execute external commands on some trigger raised by logkeys ?
I would like to auto-start logkeys when the computer is inactive for some period and not locked (let's say 2 minutes after I left without locking my computer), and to capture a picture from the webcam when more than a number of keys has been pressed (let's say 5 so that no screenshot is taken when typing "llkk").

I can write a wrapper to auto-start logkeys when I want, and I can take and save a video snapshot automatically, but I'm not sure how to trigger the snapshot capturing only when I want it

**Comment by kernc** [comment]
The output log file seems to be [flushed after every keystroke](https://github.com/kernc/logkeys/blob/02ad0021d7b4f84adefceb1cdd8e85bcd31226e7/src/logkeys.cc#L654-L655), so in your wrapper script you could iteratively observe the file size in bytes and compare it to initial file size when logging started?
```bash
stat --format='%s' logkeys.log
```

**Comment by kernc** [comment]
If you make something useful, why not share your script here. :smiley:
