### ISSUE TITLE
Output keys are duplicated

### ISSUE THREAD

**Issue by minhducsun2002** [kernc/logkeys#197]
Typing `root` yields `rroooott`. Any solution?

**Comment by buphomet** [comment]
Is this the output from 

```
tail --follow /var/log/logkeys.log

```

If yes, then this is accurate.

What you're probably getting is echo from the terminal and output from logkeys itself.

This is most probably not an issue, it is the expected behaviour from running `tail --follow /var/log/logkeys`

**Comment by minhducsun2002** [comment]
Well let me try it again with the `tail` and the testing window separately.

**Comment by buphomet** [comment]
> Well let me try it again with the `tail` and the testing window separately.

That would be great. Kindly report back.

**Comment by minhducsun2002** [comment]
Whoops, you were right.
