### ISSUE TITLE
After running autogen.sh I get the message aclocal not found

### ISSUE THREAD

**Issue by Braber01** [kernc/logkeys#198]
not sure what I can do to fix this or anythng a

**Comment by kernc** [comment]
[Search](https://www.google.com/search?q=aclocal+not+found) led me to this [answer](https://askubuntu.com/questions/45480/how-do-i-install-aclocal):
```bash
sudo apt-get install autotools-dev
```
Indeed, this should be better documented:
https://github.com/kernc/logkeys/blob/c1820838839d4ac4d0e3559f263a740a76aa8645/INSTALL#L17

**Comment by Israel-Laguan** [comment]
Later, the way to install it in debian 9 is (use sudo or su if needed):
```
./autogen.sh
mkdir build
cd build/
../configure
make
su
make install
exit
man logkeys
```
If documentation appears all must be good to go.
