### ISSUE TITLE
Logkeys empty log file 

### ISSUE THREAD

**Issue by alish-nyc** [kernc/logkeys#199]
Hi everyone! I installed successfully logkeys on the CentOS7, and looks like it's working, but when I run sudo logkeys -s it started, and then I stopped it sudo logkeys -s, and when I'm checking the output in the /var/log/logkeys.log I see only the 'Logging started...' and 'Logging stopped.  Without any keypress "contents"  I checked my device input and I'v got this --> /dev/input/event2

Your Troubleshooting says:   It's very likely that logkeys got your device id wrong. I checked my 
 I connected to my Linux Server via SSH app Putty. So I'm using my keyboard remotely. 
Please let me know how to fix this issue. 

Thanks in advance.

**Comment by october21** [comment]
Hi! I think logkeys not working via SSH

**Comment by alish-nyc** [comment]
@october21  Yes that's right it doesn't work remotely via SSH, I just use it on the CentOS directly and it's working correctly, via SSH not working! This is my findings, hope it will helps to others.

Thanks!
