### ISSUE TITLE
sudo ./autogen.sh = ... aclocal: not found

### ISSUE THREAD

**Issue by nam108** [kernc/logkeys#209]
Hi

I was trying to build logkeys on my machine (Mint 19.2 64bit) and I guess failed at

> sudo ./autogen.sh

which gave me:

> Regenerating autotools files ...
> ./autogen.sh: 10: ./autogen.sh: aclocal: not found
> ... done.  Now please do the following:
> 
>    cd build; ../configure; make; su; make install

and the "build" folder only had file ".gitignore"

**Comment by kernc** [comment]
Have you followed the instructions?

https://github.com/kernc/logkeys/blob/1e452856c71ca26a7702dc9ea128324abcb227f1/INSTALL#L10-L17

**Comment by nam108** [comment]
Yes.
I've "googled" it and I was missing automake

> sudo apt-get install automake

Thanks
