### ISSUE TITLE
logkeys autogen.sh script doesn't work 

### ISSUE THREAD

**Issue by vipulme** [kernc/logkeys#213]
Hello Team,

Files doesn't  generated in build directory.
( cd build; ../configure; make; su; make install)
any solution..

**Comment by jubalh** [comment]
Did you read https://github.com/kernc/logkeys/blob/master/INSTALL ?

**Comment by vipulme** [comment]
Yes i read.
After  run ./autogen.sh build directory showing empty (configure doesn't
showing)

**Comment by kernc** [comment]
@vipulme Can you paste a record of shell session, showing the error?

**Comment by kernc** [comment]
> After  run ./autogen.sh build directory showing empty (configure doesn't showing)

_configure_ script is still in the project root. You just run it from the build dir:
```bash
cd build
../configure  # Mind the parent directory
```
This is called an [out-of-tree build](https://www.google.com/search?q=out+of+tree+build).
