### ISSUE TITLE
make: *** No rule to make target 'install'. Stop.

### ISSUE THREAD

**Issue by heysharique** [kernc/logkeys#235]
On Ubuntu 20.04 I am [installing](https://github.com/kernc/logkeys/blob/master/INSTALL) logkeys. **make install** command is throwing - make: *** No rule to make target 'install'. Stop.

**Comment by heysharique** [comment]
Okay, thank you.
I tried finding make file, but couldn't. Where should it be present?

**Comment by jubalh** [comment]
You did follow the instructions in the `INSTALL` file that you linked above, right? You call the autogen script and then run configure then the file will be generated.

**Comment by heysharique** [comment]
Yes, okay.
