### ISSUE TITLE
logkeys is not logging any more

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#60]
```
Hi, all of the sudden logkeys stoped working and it's not loggin anymore.

The version used is 0.1.1a on Arch GNU/Linux distro, using kernel 2.6.39.2.

I strace-ed it and it seem that whenever logkeys tries to write to my output 
logfile it gets a "EBADF (Bad file descriptor)" error.

I'm attaching the output of strace and dumpkeys.
```

Original issue reported on code.google.com by `n3tpr...@gmail.com` on 3 Jul 2011 at 4:04

Attachments:
- [strace.output](https://storage.googleapis.com/google-code-attachments/logkeys/issue-60/comment-0/strace.output)
- [dumpkeys.output](https://storage.googleapis.com/google-code-attachments/logkeys/issue-60/comment-0/dumpkeys.output)

**Comment by jzohrab** [comment]
Is this not merged in to master?

**Comment by kernc** [comment]
Ah, indeed, it appears to be. :sweat_smile: Sorry.
