### ISSUE TITLE
Ubuntu 12.04 US English key map

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#88]
```
Here is the keymap that I used for Ubuntu 12.04.  The -u option didn't appear 
to map correctly.
```

Original issue reported on code.google.com by `don.sand...@gmail.com` on 8 Jun 2012 at 6:41

Attachments:
* [1204_lang.map](https://storage.googleapis.com/google-code-attachments/logkeys/issue-88/comment-0/1204_lang.map)

**Comment by SachitNayak** [comment]
Thanks a lot guys! it worked perfectly for me!!!
The default us keymap is messed up or obsolete i guess... thanks a lot!
